version: "3.9"
services:
  agent-api:
    build: .
    image: dsn-bct-llm-agent:latest
    container_name: dsn_bct_agent
    ports:
      - "8000:8000"
    environment:
      - MODEL_ID=Qwen/Qwen3-4B
      - EMBED_ID=BAAI/bge-small-en-v1.5
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ./artifacts:/app/artifacts
      - hf_cache:/app/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
volumes:
  hf_cache:
